# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: iotg
      url-base: https://github.com/intel-innersource
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos


  #
  # Please add items below based on alphabetical order
  projects:

    - name: os.rtos.zephyr.iot.zephyr
      path: zephyr
      revision: zephyr_non_upstream_2.7.2
      remote: iotg
      import:
        name-whitelist:
          - ci-tools
          - cmsis
          - civetweb
          - fatfs
          - hal_st
          - littlefs
          - mbedtls
          - mipi-sys-t
          - net-tools
          - segger
          - tinycbor
          - tinycrypt

    - name: os.rtos.zephyr.iot.hal-intel
      revision: ia_opensource
      remote: iotg
      path: modules/hal/intel
    - name: os.rtos.zephyr.iot.zephyr-iotg
      revision: ia_opensource
      remote: iotg
      path: zephyr-iotg

  self:
    path: zephyr-ia
    west-commands: scripts/west-commands.yml
