# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: intel
      url-base: https://github.com/intel
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos


  #
  # Please add items below based on alphabetical order
  projects:

    - name: zephyr
      path: zephyr
      revision: intel-ehl-ia
      remote: intel
      import:
        name-whitelist:
          - ci-tools
          - civetweb
          - fatfs
          - mbedtls
          - net-tools
          - segger
          - tinycrypt

    - name: sedi-drivers
      revision: zephyr-ia
      remote: intel
      path: modules/hal/intel
    - name: rtos-if-drivers
      revision: zephyr-ia
      remote: intel
      path: zephyr-iotg

  self:
    path: zephyr-ia
    west-commands: scripts/west-commands.yml
